# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import node_pb2 as node__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in node_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/awg.NodeControl/Health',
                request_serializer=node__pb2.HealthRequest.SerializeToString,
                response_deserializer=node__pb2.HealthReply.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_unary(
                '/awg.NodeControl/ListUsers',
                request_serializer=node__pb2.ListUsersRequest.SerializeToString,
                response_deserializer=node__pb2.ListUsersReply.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/awg.NodeControl/CreateUser',
                request_serializer=node__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=node__pb2.CreateUserReply.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/awg.NodeControl/DeleteUser',
                request_serializer=node__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=node__pb2.DeleteUserReply.FromString,
                _registered_method=True)
        self.GetUserConfig = channel.unary_unary(
                '/awg.NodeControl/GetUserConfig',
                request_serializer=node__pb2.GetUserConfigRequest.SerializeToString,
                response_deserializer=node__pb2.GetUserConfigReply.FromString,
                _registered_method=True)
        self.GetUserQr = channel.unary_unary(
                '/awg.NodeControl/GetUserQr',
                request_serializer=node__pb2.GetUserQrRequest.SerializeToString,
                response_deserializer=node__pb2.GetUserQrReply.FromString,
                _registered_method=True)


class NodeControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserQr(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=node__pb2.HealthRequest.FromString,
                    response_serializer=node__pb2.HealthReply.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=node__pb2.ListUsersRequest.FromString,
                    response_serializer=node__pb2.ListUsersReply.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=node__pb2.CreateUserRequest.FromString,
                    response_serializer=node__pb2.CreateUserReply.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=node__pb2.DeleteUserRequest.FromString,
                    response_serializer=node__pb2.DeleteUserReply.SerializeToString,
            ),
            'GetUserConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserConfig,
                    request_deserializer=node__pb2.GetUserConfigRequest.FromString,
                    response_serializer=node__pb2.GetUserConfigReply.SerializeToString,
            ),
            'GetUserQr': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserQr,
                    request_deserializer=node__pb2.GetUserQrRequest.FromString,
                    response_serializer=node__pb2.GetUserQrReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'awg.NodeControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('awg.NodeControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/awg.NodeControl/Health',
            node__pb2.HealthRequest.SerializeToString,
            node__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/awg.NodeControl/ListUsers',
            node__pb2.ListUsersRequest.SerializeToString,
            node__pb2.ListUsersReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/awg.NodeControl/CreateUser',
            node__pb2.CreateUserRequest.SerializeToString,
            node__pb2.CreateUserReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/awg.NodeControl/DeleteUser',
            node__pb2.DeleteUserRequest.SerializeToString,
            node__pb2.DeleteUserReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/awg.NodeControl/GetUserConfig',
            node__pb2.GetUserConfigRequest.SerializeToString,
            node__pb2.GetUserConfigReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserQr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/awg.NodeControl/GetUserQr',
            node__pb2.GetUserQrRequest.SerializeToString,
            node__pb2.GetUserQrReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
