# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: node.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'node.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnode.proto\x12\x03\x61wg\"\x0f\n\rHealthRequest\"@\n\x0bHealthReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t\"\x12\n\x10ListUsersRequest\"\xa5\x01\n\x04User\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0binternal_ip\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t\x12\x13\n\x0btransfer_rx\x18\x05 \x01(\t\x12\x13\n\x0btransfer_tx\x18\x06 \x01(\t\x12\x16\n\x0elast_handshake\x18\x07 \x01(\t\x12\x11\n\tis_online\x18\x08 \x01(\x08\"*\n\x0eListUsersReply\x12\x18\n\x05users\x18\x01 \x03(\x0b\x32\t.awg.User\"!\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\":\n\x0f\x43reateUserReply\x12\x17\n\x04user\x18\x01 \x01(\x0b\x32\t.awg.User\x12\x0e\n\x06\x63onfig\x18\x02 \x01(\t\"&\n\x11\x44\x65leteUserRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"\x11\n\x0f\x44\x65leteUserReply\")\n\x14GetUserConfigRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"8\n\x12GetUserConfigReply\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x11\n\tfile_name\x18\x02 \x01(\t\"%\n\x10GetUserQrRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"\x1d\n\x0eGetUserQrReply\x12\x0b\n\x03png\x18\x01 \x01(\x0c\x32\xec\x02\n\x0bNodeControl\x12.\n\x06Health\x12\x12.awg.HealthRequest\x1a\x10.awg.HealthReply\x12\x37\n\tListUsers\x12\x15.awg.ListUsersRequest\x1a\x13.awg.ListUsersReply\x12:\n\nCreateUser\x12\x16.awg.CreateUserRequest\x1a\x14.awg.CreateUserReply\x12:\n\nDeleteUser\x12\x16.awg.DeleteUserRequest\x1a\x14.awg.DeleteUserReply\x12\x43\n\rGetUserConfig\x12\x19.awg.GetUserConfigRequest\x1a\x17.awg.GetUserConfigReply\x12\x37\n\tGetUserQr\x12\x15.awg.GetUserQrRequest\x1a\x13.awg.GetUserQrReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=19
  _globals['_HEALTHREQUEST']._serialized_end=34
  _globals['_HEALTHREPLY']._serialized_start=36
  _globals['_HEALTHREPLY']._serialized_end=100
  _globals['_LISTUSERSREQUEST']._serialized_start=102
  _globals['_LISTUSERSREQUEST']._serialized_end=120
  _globals['_USER']._serialized_start=123
  _globals['_USER']._serialized_end=288
  _globals['_LISTUSERSREPLY']._serialized_start=290
  _globals['_LISTUSERSREPLY']._serialized_end=332
  _globals['_CREATEUSERREQUEST']._serialized_start=334
  _globals['_CREATEUSERREQUEST']._serialized_end=367
  _globals['_CREATEUSERREPLY']._serialized_start=369
  _globals['_CREATEUSERREPLY']._serialized_end=427
  _globals['_DELETEUSERREQUEST']._serialized_start=429
  _globals['_DELETEUSERREQUEST']._serialized_end=467
  _globals['_DELETEUSERREPLY']._serialized_start=469
  _globals['_DELETEUSERREPLY']._serialized_end=486
  _globals['_GETUSERCONFIGREQUEST']._serialized_start=488
  _globals['_GETUSERCONFIGREQUEST']._serialized_end=529
  _globals['_GETUSERCONFIGREPLY']._serialized_start=531
  _globals['_GETUSERCONFIGREPLY']._serialized_end=587
  _globals['_GETUSERQRREQUEST']._serialized_start=589
  _globals['_GETUSERQRREQUEST']._serialized_end=626
  _globals['_GETUSERQRREPLY']._serialized_start=628
  _globals['_GETUSERQRREPLY']._serialized_end=657
  _globals['_NODECONTROL']._serialized_start=660
  _globals['_NODECONTROL']._serialized_end=1024
# @@protoc_insertion_point(module_scope)
